name: Build images

on:
  push:
    # branches:
    #   - master

env:
  DOCKER_REGISTRY: ghcr.io/ibiqlik

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile: [dev]
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_USER} --password-stdin
          docker build -t ${DOCKER_REGISTRY}/${{ matrix.dockerfile }}:latest ${{ matrix.dockerfile }}/
          docker push ${DOCKER_REGISTRY}/${{ matrix.dockerfile }}:latest
